#!/bin/bash
docker run -ti hunan131/wl-ml-gpu-v1 \
    bash -c 'export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}; export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}; bash'